logging:
    level:
        org:
            atmosphere: warn
        de.hub28: debug
    pattern:
        console: "[%thread] %-5level %logger{36} - %msg%n"

server:
    port: ${PORT:8080}

spring:
    mustache:
        check-template-location: false
vaadin:
    launch-browser: true
    whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,de.hub28
